title = "Riptide"
baseURL = "https://riptidetheband.com"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "A Blues/Rock cover band from Albert Lea, Minnesota"
  facebook = "https://facebook.com/riptidetheband"
  twitter = "https://twitter.com/riptideband2"
  youtube = "https://www.youtube.com/channel/UC9elo26pfthgP96EA3GBzUA?view_as=subscriber"

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "images/header.jpg"
  recent_posts_number = 2
